In [35]:
import numpy as np

In [36]:
# experimenting wiht how zip works
input = [0.1,0.2,0.3,0.4]
weights = [[0.2,0.1,0.3,0.4],[0.4,0.6,0.1,0.9],[0.7,0.6,0.1,0.1]]
bias = [0.2,0.3,0.4]

layer_output = []
for n_weight, n_bias in zip(weights, bias):
    n_output = 0
    for n_input, weight in zip(input, n_weight):
        n_output += n_input * weight
    n_output += n_bias
    layer_output.append(n_output)
print(layer_output)

[0.49000000000000005, 0.8500000000000001, 0.66]


In [37]:
# testing how transposes are handled in numpy
inputs = [[1.0, 2.0, 3.0, 2.5],
          [2.0, 5.0, -1.0, 2.0],
          [-1.5, 2.7, 3.3, -0.8]]
weights = [[0.2, 0.8, -0.5, 1.0],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]
biases = [2.0, 3.0, 0.5]

weights2 = [[0.2, 0.8, -0.5],
           [0.5, -0.91, 0.26],
           [-0.26, -0.27, 0.17]]

biases2 = [2.0, 3.0, 0.5]
output1 = np.dot(inputs, np.array(weights).T) + biases
print(output1)
output2 = np.dot(output1, np.array(weights2).T) + biases2
print(output2)

[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]
[[ 2.7355   4.919   -0.66925]
 [ 2.232    9.1491  -1.2913 ]
 [ 3.1098   2.75535 -0.14595]]


In [38]:
# testing how arrays and matrices are handled differently in numpy
a = [1, 2, 3]
b = [2, 3, 4]
output = np.dot(a,np.array(b).T)
print(output)

output2 = np.dot(np.array([a]),np.array([b]).T)
print(output2)

output3 = np.dot(np.array(a),np.array([b]).T)
print(output3)

20
[[20]]
[20]


In [39]:
inputs = [[1, 2, 3, 2.5],
        [2., 5., -1., 2],
        [-1.5, 2.7, 3.3, -0.8]]
weights = [[0.2, 0.8, -0.5, 1],
            [0.5, -0.91, 0.26, -0.5],
            [-0.26, -0.27, 0.17, 0.87]]
biases = [2, 3, 0.5]
weights2 = [[0.1, -0.14, 0.5],
            [-0.5, 0.12, -0.33],
            [-0.44, 0.73, -0.13]]
biases2 = [-1, 2, -0.5]

# i want to make an output

layer1_output = np.dot(inputs, np.array(weights).T) + biases
print(layer1_output)

layer2_output = np.dot(layer1_output, np.array(weights2).T) + biases2
print(layer2_output)

[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]
[[ 0.5031  -1.04185 -2.03875]
 [ 0.2434  -2.7332  -5.7633 ]
 [-0.99314  1.41254 -0.35655]]


In [48]:
import numpy as np
import nnfs
from nnfs.datasets import spiral_data

nnfs.init()

ModuleNotFoundError: No module named 'nnfs.datasets'; 'nnfs' is not a package

: 